CREATE DATABASE QuanLyNhanSu
USE QuanLyNhanSu

CREATE TABLE QuanLy (
	MaQL VARCHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(5),
	NgaySinh VARCHAR(15),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15),
	Email VARCHAR(50)
)

CREATE TABLE PhongBan (
	MaPB VARCHAR(15) NOT NULL PRIMARY KEY,
	TenPB NVARCHAR(50),
	NgayLap VARCHAR(15),
	SDT VARCHAR(15),
	MaQL VARCHAR(15) FOREIGN KEY REFERENCES QuanLy(MaQL)
)

CREATE TABLE NhanVien (
	MaNV VARCHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(5),
	NgaySinh VARCHAR(15),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15),
	Email VARCHAR(50),
	ChucVu NVARCHAR(50),
	ViTriCongViec NVARCHAR(50),
	MaPB VARCHAR(15) FOREIGN KEY REFERENCES PhongBan(MaPB)
)

CREATE TABLE DuAn (
	MaDA VARCHAR(15) NOT NULL PRIMARY KEY,
	TenDA NVARCHAR(50),
	SoNV INT,
	MoTaDA NVARCHAR(100),
	MaPB VARCHAR(15) FOREIGN KEY REFERENCES PhongBan(MaPB)
)

CREATE TABLE ChamCong (	
	MaCC INT IDENTITY(1, 1) PRIMARY KEY,
	NgayLam INT,
	ThangLam INT,
	NamLam INT,
	TrangThai NVARCHAR(50),
	GhiChu NVARCHAR(50),
	MaNV VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES NhanVien(MaNV)
)