CREATE DATABASE QuanLyNhanSu
USE QuanLyNhanSu

CREATE TABLE QuanLy (
	MaQL VARCHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(5),
	NgaySinh VARCHAR(15),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15),
	Email VARCHAR(50)
)

CREATE TABLE PhongBan (
	MaPB VARCHAR(15) NOT NULL PRIMARY KEY,
	TenPB NVARCHAR(50),
	NgayLap VARCHAR(15),
	SDT VARCHAR(15),
	MaQL VARCHAR(15) FOREIGN KEY REFERENCES QuanLy(MaQL)
)

CREATE TABLE NhanVien (
	MaNV VARCHAR(15) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(5),
	NgaySinh VARCHAR(15),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15),
	Email VARCHAR(50),
	ChucVu NVARCHAR(50),
	ViTriCongViec NVARCHAR(50),
	MaPB VARCHAR(15) FOREIGN KEY REFERENCES PhongBan(MaPB)
)

CREATE TABLE DuAn (
	MaDA VARCHAR(15) NOT NULL PRIMARY KEY,
	TenDA NVARCHAR(50),
	SoNV INT,
	MoTaDA NVARCHAR(100),
	MaPB VARCHAR(15) FOREIGN KEY REFERENCES PhongBan(MaPB)
)

CREATE TABLE ChamCong (
	MaNV VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES NhanVien(MaNV),
	MaDA VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES DuAn(MaDA),
	SoNgayLam FLOAT,
	PRIMARY KEY (MaNV, MaDA)
)

CREATE TABLE TaiKhoanDangNhap (
	TenTK NVARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau NVARCHAR(50),
	MaQL VARCHAR(15) FOREIGN KEY REFERENCES QuanLy(MaQL)
)
select * from QuanLy
select * from TaiKhoanDangNhap
insert into QuanLy values ('QL0001', N'Nguyễn Xuân Mạnh', N'Nam', '29/09/2003', N'Khánh Thượng Ba Vì Hà Nội', '0352593469', '20210794@eaut.edu.vn')
insert into TaiKhoanDangNhap values ('XuanManh', '123', 'QL0001')
select TenTK, MatKhau from TaiKhoanDangNhap
select * from NhanVien